services:
  mysql:
    image: mysql:8.0
    container_name: frutos_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: "fru705@db_homolog"
      MYSQL_DATABASE: "frutos_aggregator_db"

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: